### PR TITLE
Dockerize project's development environment

### PR DESCRIPTION
**Pull request by igordavydsson**
No refs

### CODE REVIEW

**Comment by igordavydsson** [comment]
@jussiarpalahti alrighty! 3.6 it is. 🙂

**Comment by igordavydsson** [comment]
Prerequisites in README said `>=3.4`, so that is why I thought it should be 3.4 🙂

**Comment by igordavydsson** [comment]
Travis seems to be glitching. The job should go fine, once restarted, I guess.

**Comment by jussiarpalahti** [comment]
Well, 3.4 what has been used since 16.04 Ubuntu, but we're transitioning to 18.04. In any case I'd trust tests check backwards compatibility to reasonable extent.

**Pull request merged**
